#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🧹 Styling, testing and building your project before committing..."

# Check Prettier
npm run check-format ||
(
    echo "❌ Prettier Check Failed. Run: npm run format, add changes, and try commit again"
    false;
)

# Check ESLint
npm run check-lint ||
(
    echo "❌ ESLint Check Failed. Fix the issues listed above, add changes, and try commit again"
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo "❌ Type check failed. Fix the issues listed above, add changes, and try commit again"
    false;
)

# Build
npm run build ||
(
    echo "❌ Build failed. See errors above"
    false;
)

echo "✅ Success! Ready to commit 🚀"

echo "🔄 Auto staging changes before commit..."
git add .